theme: jekyll-theme-minimal
title: "Computational Genomics"
repository: eran-halperin/CSCI-GA3033-135CompGenomics
description: "Statistical Foundations to Genomic Foundational Models"

# Custom metadata
instructor: "Eran Halperin, PhD"
office: "One Park Ave, Manhattan"
lab: "NYU HPC Cloud Bursting"

# Navigation
nav:
  - title: "Syllabus"
    url: /
  - title: "Project & Presentation"
    url: /project
  - title: "HPC Guide"
    url: /hpc_guide
